"""Replaced period with interval

Revision ID: 01600fd4bd86
Revises: cbe8a55da600
Create Date: 2024-02-15 16:27:30.201163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01600fd4bd86'
down_revision = 'cbe8a55da600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_user_activity', sa.Column('interval', sa.String(length=64), nullable=False))
    op.drop_index('ix_service_user_activity_period', table_name='service_user_activity')
    op.create_index(op.f('ix_service_user_activity_interval'), 'service_user_activity', ['interval'], unique=False)
    op.drop_column('service_user_activity', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_user_activity', sa.Column('period', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_service_user_activity_interval'), table_name='service_user_activity')
    op.create_index('ix_service_user_activity_period', 'service_user_activity', ['period'], unique=False)
    op.drop_column('service_user_activity', 'interval')
    # ### end Alembic commands ###
