"""Addeded comment vote model

Revision ID: 04a78ebfda3d
Revises: bc540d13f1d1
Create Date: 2024-01-28 21:58:47.556044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a78ebfda3d'
down_revision = 'bc540d13f1d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_comment_votes',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['service_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_comment_votes')
    # ### end Alembic commands ###
