"""Added translated_ua field to anime

Revision ID: 1245c32b25c6
Revises: e64db5c39606
Create Date: 2023-12-29 01:52:58.555221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1245c32b25c6"
down_revision = "e64db5c39606"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_anime",
        sa.Column(
            "translated_ua",
            sa.Boolean(),
            server_default=sa.schema.DefaultClause("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_anime", "translated_ua")
    # ### end Alembic commands ###
