"""Removed unique_constraint from voice

Revision ID: 13a8c8325dde
Revises: dc26b7f68dd5
Create Date: 2023-07-21 03:54:00.649661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a8c8325dde'
down_revision = 'dc26b7f68dd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_content_anime_voices_character_id_person_id_anime_i_key', 'service_content_anime_voices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('service_content_anime_voices_character_id_person_id_anime_i_key', 'service_content_anime_voices', ['character_id', 'person_id', 'anime_id'])
    # ### end Alembic commands ###
