"""Added last change fields to user

Revision ID: 1841b8bc0b1b
Revises: d8b5ce4a470d
Create Date: 2023-11-21 18:10:59.606502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1841b8bc0b1b'
down_revision = 'd8b5ce4a470d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_users', sa.Column('last_username_change', sa.DateTime(), nullable=True))
    op.add_column('service_users', sa.Column('last_email_change', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_users', 'last_email_change')
    op.drop_column('service_users', 'last_username_change')
    # ### end Alembic commands ###
