"""Added entries field to collection

Revision ID: 1a409d817c42
Revises: 55e4300b8247
Create Date: 2024-02-23 14:46:54.554176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a409d817c42'
down_revision = '55e4300b8247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_collections', sa.Column('entries', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_collections', 'entries')
    # ### end Alembic commands ###
