"""Added weight to AnimeStaff

Revision ID: 1dd385e4cf87
Revises: 9243b73ca2d0
Create Date: 2023-12-26 00:24:37.194343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd385e4cf87'
down_revision = '9243b73ca2d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime_staff', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_anime_staff', 'weight')
    # ### end Alembic commands ###
