"""Removed article content model

Revision ID: c448e3d92c92
Revises: cd943422c3a7
Create Date: 2024-12-23 16:07:27.255837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c448e3d92c92'
down_revision = 'cd943422c3a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_articles_content')
    op.add_column('service_articles', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('service_articles', sa.Column('content_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_articles', 'content_id')
    op.drop_column('service_articles', 'content_type')
    op.create_table('service_articles_content',
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['service_articles.id'], name='service_articles_content_article_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_articles_content_pkey')
    )
    # ### end Alembic commands ###
