"""Added category to tag

Revision ID: 3027a7fff9ca
Revises: 3a37a0ecfd46
Create Date: 2024-12-25 21:05:54.628427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3027a7fff9ca'
down_revision = '3a37a0ecfd46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tags', sa.Column('category', sa.String(), nullable=False))
    op.create_index(op.f('ix_service_tags_category'), 'service_tags', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_tags_category'), table_name='service_tags')
    op.drop_column('service_tags', 'category')
    # ### end Alembic commands ###
