"""Added index to collection tags

Revision ID: d24be66ce4d7
Revises: a04637ec3f4a
Create Date: 2024-12-23 22:28:26.890139

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "d24be66ce4d7"
down_revision = "a04637ec3f4a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_collection_tags_gin",
        "service_collections",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_collection_tags_gin",
        table_name="service_collections",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
