"""Removed franchise from anime

Revision ID: 669174c7334c
Revises: 801921931ef3
Create Date: 2024-06-05 17:54:55.594158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669174c7334c'
down_revision = '801921931ef3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_content_anime_franchise_id', table_name='service_content_anime')
    op.drop_constraint('service_content_anime_franchise_id_fkey', 'service_content_anime', type_='foreignkey')
    op.drop_column('service_content_anime', 'franchise_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime', sa.Column('franchise_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('service_content_anime_franchise_id_fkey', 'service_content_anime', 'service_content_anime_franchises', ['franchise_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_service_content_anime_franchise_id', 'service_content_anime', ['franchise_id'], unique=False)
    # ### end Alembic commands ###
