"""Added private field to comment

Revision ID: 47b1673a82ea
Revises: 0c8a96ac77c9
Create Date: 2024-05-12 02:59:17.360430

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47b1673a82ea"
down_revision = "0c8a96ac77c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_comments",
        sa.Column(
            "private", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_comments", "private")
    # ### end Alembic commands ###
