"""Added indexes to image and upload path

Revision ID: cd943422c3a7
Revises: cdb9b148e545
Create Date: 2024-12-23 00:27:27.226056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd943422c3a7'
down_revision = 'cdb9b148e545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_images_path_key', 'service_images', type_='unique')
    op.create_index(op.f('ix_service_images_path'), 'service_images', ['path'], unique=True)
    op.create_index(op.f('ix_service_uploads_path'), 'service_uploads', ['path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_uploads_path'), table_name='service_uploads')
    op.drop_index(op.f('ix_service_images_path'), table_name='service_images')
    op.create_unique_constraint('service_images_path_key', 'service_images', ['path'])
    # ### end Alembic commands ###
