"""Removed old tags field

Revision ID: 0c90ea0fe326
Revises: eac1e35f43f3
Create Date: 2024-12-23 22:21:52.490482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c90ea0fe326'
down_revision = 'eac1e35f43f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_articles', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_articles', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
