"""Introduce third-party clients

Revision ID: 21009df4f5f5
Revises: 4c13fdf8868d
Create Date: 2024-07-26 13:56:21.385422

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "21009df4f5f5"
down_revision = "4c13fdf8868d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_clients",
        sa.Column("secret", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["service_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_auth_token_requests",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("expiration", sa.DateTime(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["service_clients.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["service_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "service_auth_tokens", sa.Column("client_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "service_auth_tokens",
        sa.Column(
            "scope",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "service_auth_tokens_client_id_fkey",
        "service_auth_tokens",
        "service_clients",
        ["client_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "service_auth_tokens_client_id_fkey",
        "service_auth_tokens",
        type_="foreignkey",
    )
    op.drop_column("service_auth_tokens", "scope")
    op.drop_column("service_auth_tokens", "client_id")
    op.drop_table("service_auth_token_requests")
    op.drop_table("service_clients")
    # ### end Alembic commands ###
