"""Added novel models

Revision ID: 7c68bcc6ca7b
Revises: a098f38e56e9
Create Date: 2024-06-05 23:35:18.226126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c68bcc6ca7b'
down_revision = 'a098f38e56e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_content_novel',
    sa.Column('title_original', sa.String(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('title_ua', sa.String(), nullable=True),
    sa.Column('synopsis_en', sa.String(), nullable=True),
    sa.Column('synopsis_ua', sa.String(), nullable=True),
    sa.Column('aggregator_updated', sa.DateTime(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('translated_ua', sa.Boolean(), nullable=False),
    sa.Column('needs_update', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=True),
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=True),
    sa.Column('external', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('franchise_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ignored_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_search_update', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['service_content_franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_novel_content_id'), 'service_content_novel', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_novel_franchise_id'), 'service_content_novel', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_service_content_novel_image_id'), 'service_content_novel', ['image_id'], unique=False)
    op.create_index(op.f('ix_service_content_novel_mal_id'), 'service_content_novel', ['mal_id'], unique=False)
    op.create_index(op.f('ix_service_content_novel_media_type'), 'service_content_novel', ['media_type'], unique=False)
    op.create_index(op.f('ix_service_content_novel_slug'), 'service_content_novel', ['slug'], unique=False)
    op.create_index(op.f('ix_service_content_novel_status'), 'service_content_novel', ['status'], unique=False)
    op.create_index(op.f('ix_service_content_novel_year'), 'service_content_novel', ['year'], unique=False)
    op.create_table('service_content_novel_authors',
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('novel_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['service_content_novel.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['service_content_people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'novel_id')
    )
    op.create_index(op.f('ix_service_content_novel_authors_novel_id'), 'service_content_novel_authors', ['novel_id'], unique=False)
    op.create_index(op.f('ix_service_content_novel_authors_person_id'), 'service_content_novel_authors', ['person_id'], unique=False)
    op.create_table('service_content_novel_characters',
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('novel_id', sa.Uuid(), nullable=True),
    sa.Column('main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['service_content_characters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['service_content_novel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'novel_id')
    )
    op.create_index(op.f('ix_service_content_novel_characters_character_id'), 'service_content_novel_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_service_content_novel_characters_novel_id'), 'service_content_novel_characters', ['novel_id'], unique=False)
    op.create_table('service_relation_genres_novel',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['service_content_genres.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['service_content_novel.id'], ),
    sa.PrimaryKeyConstraint('novel_id', 'genre_id')
    )
    op.create_table('service_relation_novel_magazines',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('magazine_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['magazine_id'], ['service_content_magazines.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['service_content_novel.id'], ),
    sa.PrimaryKeyConstraint('novel_id', 'magazine_id')
    )
    op.create_table('service_relation_novel_author_roles',
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['service_content_novel_authors.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['service_content_author_roles.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_relation_novel_author_roles')
    op.drop_table('service_relation_novel_magazines')
    op.drop_table('service_relation_genres_novel')
    op.drop_index(op.f('ix_service_content_novel_characters_novel_id'), table_name='service_content_novel_characters')
    op.drop_index(op.f('ix_service_content_novel_characters_character_id'), table_name='service_content_novel_characters')
    op.drop_table('service_content_novel_characters')
    op.drop_index(op.f('ix_service_content_novel_authors_person_id'), table_name='service_content_novel_authors')
    op.drop_index(op.f('ix_service_content_novel_authors_novel_id'), table_name='service_content_novel_authors')
    op.drop_table('service_content_novel_authors')
    op.drop_index(op.f('ix_service_content_novel_year'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_novel_status'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_novel_slug'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_novel_media_type'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_novel_mal_id'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_novel_image_id'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_novel_franchise_id'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_novel_content_id'), table_name='service_content_novel')
    op.drop_table('service_content_novel')
    # ### end Alembic commands ###
