"""Removed legacy genres

Revision ID: 4882ac82d08b
Revises: 8e32142fab6e
Create Date: 2024-06-05 20:51:22.512090

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4882ac82d08b"
down_revision = "8e32142fab6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_relation_manga_genres")
    op.drop_table("service_relation_anime_genres")
    op.drop_index(
        "ix_service_content_anime_genres_content_id",
        table_name="service_content_anime_genres",
    )
    op.drop_index(
        "ix_service_content_anime_genres_slug",
        table_name="service_content_anime_genres",
    )
    op.drop_index(
        "ix_service_content_anime_genres_type",
        table_name="service_content_anime_genres",
    )
    op.drop_table("service_content_anime_genres")
    op.drop_index(
        "ix_service_content_manga_genres_content_id",
        table_name="service_content_manga_genres",
    )
    op.drop_index(
        "ix_service_content_manga_genres_slug",
        table_name="service_content_manga_genres",
    )
    op.drop_index(
        "ix_service_content_manga_genres_type",
        table_name="service_content_manga_genres",
    )
    op.drop_table("service_content_manga_genres")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_relation_manga_genres",
        sa.Column("manga_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("genre_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["service_content_manga_genres.id"],
            name="service_relation_manga_genres_genre_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["manga_id"],
            ["service_content_manga.id"],
            name="service_relation_manga_genres_manga_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "manga_id", "genre_id", name="service_relation_manga_genres_pkey"
        ),
    )
    op.create_table(
        "service_content_manga_genres",
        sa.Column(
            "name_en", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "name_ua", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "type", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "content_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="service_content_manga_genres_pkey"),
    )
    op.create_index(
        "ix_service_content_manga_genres_type",
        "service_content_manga_genres",
        ["type"],
        unique=False,
    )
    op.create_index(
        "ix_service_content_manga_genres_slug",
        "service_content_manga_genres",
        ["slug"],
        unique=False,
    )
    op.create_index(
        "ix_service_content_manga_genres_content_id",
        "service_content_manga_genres",
        ["content_id"],
        unique=True,
    )
    op.create_table(
        "service_content_anime_genres",
        sa.Column(
            "name_en", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "name_ua", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "type", sa.VARCHAR(length=32), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "content_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="service_content_anime_genres_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_service_content_anime_genres_type",
        "service_content_anime_genres",
        ["type"],
        unique=False,
    )
    op.create_index(
        "ix_service_content_anime_genres_slug",
        "service_content_anime_genres",
        ["slug"],
        unique=False,
    )
    op.create_index(
        "ix_service_content_anime_genres_content_id",
        "service_content_anime_genres",
        ["content_id"],
        unique=True,
    )
    op.create_table(
        "service_relation_anime_genres",
        sa.Column("anime_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("genre_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["anime_id"],
            ["service_content_anime.id"],
            name="service_relation_anime_genres_anime_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["service_content_anime_genres.id"],
            name="service_relation_anime_genres_genre_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "anime_id", "genre_id", name="service_relation_anime_genres_pkey"
        ),
    )
    # ### end Alembic commands ###
