"""Manga migration

Revision ID: 68c5c7b598d1
Revises: bf31e8e30ed4
Create Date: 2024-06-01 20:07:47.824359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68c5c7b598d1'
down_revision = 'bf31e8e30ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_content_magazines',
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_magazines_content_id'), 'service_content_magazines', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_magazines_mal_id'), 'service_content_magazines', ['mal_id'], unique=False)
    op.create_index(op.f('ix_service_content_magazines_slug'), 'service_content_magazines', ['slug'], unique=False)
    op.create_table('service_content_manga',
    sa.Column('title_original', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('title_ua', sa.String(length=255), nullable=True),
    sa.Column('synopsis_en', sa.String(), nullable=True),
    sa.Column('synopsis_ua', sa.String(), nullable=True),
    sa.Column('aggregator_updated', sa.DateTime(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('translated_ua', sa.Boolean(), nullable=False),
    sa.Column('needs_update', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=True),
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=True),
    sa.Column('external', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ignored_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('needs_search_update', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_manga_content_id'), 'service_content_manga', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_manga_mal_id'), 'service_content_manga', ['mal_id'], unique=False)
    op.create_index(op.f('ix_service_content_manga_media_type'), 'service_content_manga', ['media_type'], unique=False)
    op.create_index(op.f('ix_service_content_manga_slug'), 'service_content_manga', ['slug'], unique=False)
    op.create_index(op.f('ix_service_content_manga_status'), 'service_content_manga', ['status'], unique=False)
    op.create_table('service_content_manga_author_roles',
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_ua', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_manga_author_roles_slug'), 'service_content_manga_author_roles', ['slug'], unique=False)
    op.create_table('service_content_manga_genres',
    sa.Column('name_en', sa.String(length=64), nullable=True),
    sa.Column('name_ua', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_manga_genres_content_id'), 'service_content_manga_genres', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_manga_genres_slug'), 'service_content_manga_genres', ['slug'], unique=False)
    op.create_index(op.f('ix_service_content_manga_genres_type'), 'service_content_manga_genres', ['type'], unique=False)
    op.create_table('service_relation_manga_genres',
    sa.Column('manga_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['service_content_manga_genres.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['service_content_manga.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'genre_id')
    )
    op.create_table('service_relation_manga_magazines',
    sa.Column('manga_id', sa.Uuid(), nullable=False),
    sa.Column('magazine_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['magazine_id'], ['service_content_magazines.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['service_content_manga.id'], ),
    sa.PrimaryKeyConstraint('manga_id', 'magazine_id')
    )
    op.create_table('service_content_manga_authors',
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('manga_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['manga_id'], ['service_content_manga.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['service_content_people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'manga_id')
    )
    op.create_index(op.f('ix_service_content_manga_authors_manga_id'), 'service_content_manga_authors', ['manga_id'], unique=False)
    op.create_index(op.f('ix_service_content_manga_authors_person_id'), 'service_content_manga_authors', ['person_id'], unique=False)
    op.create_table('service_content_manga_characters',
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('manga_id', sa.Uuid(), nullable=True),
    sa.Column('main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['service_content_characters.id'], ),
    sa.ForeignKeyConstraint(['manga_id'], ['service_content_manga.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'manga_id')
    )
    op.create_index(op.f('ix_service_content_manga_characters_character_id'), 'service_content_manga_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_service_content_manga_characters_manga_id'), 'service_content_manga_characters', ['manga_id'], unique=False)
    op.create_table('service_relation_manga_author_roles',
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['service_content_manga_authors.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['service_content_manga_author_roles.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_relation_manga_author_roles')
    op.drop_index(op.f('ix_service_content_manga_characters_manga_id'), table_name='service_content_manga_characters')
    op.drop_index(op.f('ix_service_content_manga_characters_character_id'), table_name='service_content_manga_characters')
    op.drop_table('service_content_manga_characters')
    op.drop_index(op.f('ix_service_content_manga_authors_person_id'), table_name='service_content_manga_authors')
    op.drop_index(op.f('ix_service_content_manga_authors_manga_id'), table_name='service_content_manga_authors')
    op.drop_table('service_content_manga_authors')
    op.drop_table('service_relation_manga_magazines')
    op.drop_table('service_relation_manga_genres')
    op.drop_index(op.f('ix_service_content_manga_genres_type'), table_name='service_content_manga_genres')
    op.drop_index(op.f('ix_service_content_manga_genres_slug'), table_name='service_content_manga_genres')
    op.drop_index(op.f('ix_service_content_manga_genres_content_id'), table_name='service_content_manga_genres')
    op.drop_table('service_content_manga_genres')
    op.drop_index(op.f('ix_service_content_manga_author_roles_slug'), table_name='service_content_manga_author_roles')
    op.drop_table('service_content_manga_author_roles')
    op.drop_index(op.f('ix_service_content_manga_status'), table_name='service_content_manga')
    op.drop_index(op.f('ix_service_content_manga_slug'), table_name='service_content_manga')
    op.drop_index(op.f('ix_service_content_manga_media_type'), table_name='service_content_manga')
    op.drop_index(op.f('ix_service_content_manga_mal_id'), table_name='service_content_manga')
    op.drop_index(op.f('ix_service_content_manga_content_id'), table_name='service_content_manga')
    op.drop_table('service_content_manga')
    op.drop_index(op.f('ix_service_content_magazines_slug'), table_name='service_content_magazines')
    op.drop_index(op.f('ix_service_content_magazines_mal_id'), table_name='service_content_magazines')
    op.drop_index(op.f('ix_service_content_magazines_content_id'), table_name='service_content_magazines')
    op.drop_table('service_content_magazines')
    # ### end Alembic commands ###
