"""Added index to article tags

Revision ID: a04637ec3f4a
Revises: 212192f8574a
Create Date: 2024-12-23 22:27:24.850364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04637ec3f4a'
down_revision = '212192f8574a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_article_tags_gin', 'service_articles', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_article_tags_gin', table_name='service_articles', postgresql_using='gin')
    # ### end Alembic commands ###
