"""Add "used" (last usage time) field to AuthToken

Revision ID: b38d06d1364e
Revises: a4d5b6174fb1
Create Date: 2024-08-12 10:36:22.543968

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b38d06d1364e"
down_revision = "a4d5b6174fb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_auth_tokens",
        sa.Column("used", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_auth_tokens", "used")
    # ### end Alembic commands ###
