"""Add client updated column

Revision ID: 96c0d6b7aeba
Revises: 21009df4f5f5
Create Date: 2024-07-26 20:28:17.602711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c0d6b7aeba'
down_revision = '21009df4f5f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_clients', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_clients', 'updated')
    # ### end Alembic commands ###
