"""Added franchise relation to anime

Revision ID: bccaf8250166
Revises: 369367fef20e
Create Date: 2024-06-05 17:57:21.877996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccaf8250166'
down_revision = '369367fef20e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime', sa.Column('franchise_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_service_content_anime_franchise_id'), 'service_content_anime', ['franchise_id'], unique=False)
    op.create_foreign_key(None, 'service_content_anime', 'service_content_franchises', ['franchise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_content_anime', type_='foreignkey')
    op.drop_index(op.f('ix_service_content_anime_franchise_id'), table_name='service_content_anime')
    op.drop_column('service_content_anime', 'franchise_id')
    # ### end Alembic commands ###
