"""Renamed name -> name_en

Revision ID: 801921931ef3
Revises: b374f1f0de11
Create Date: 2024-06-02 00:58:41.118921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801921931ef3'
down_revision = 'b374f1f0de11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_magazines', sa.Column('name_en', sa.String(), nullable=False))
    op.drop_column('service_content_magazines', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_magazines', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('service_content_magazines', 'name_en')
    # ### end Alembic commands ###
