"""Added user article stats

Revision ID: 0ef0cad343d6
Revises: 05f17232e25e
Create Date: 2024-12-26 23:47:47.306347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef0cad343d6'
down_revision = '05f17232e25e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_stats_articles',
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('news', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_stats_articles')
    # ### end Alembic commands ###
