"""Added comments_count field to articles

Revision ID: 57f348c5c8f8
Revises: d2bd8dd78891
Create Date: 2024-12-20 20:22:48.537851

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57f348c5c8f8"
down_revision = "d2bd8dd78891"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_articles",
        sa.Column(
            "comments_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_articles", "comments_count")
    # ### end Alembic commands ###
