"""More tag model updates

Revision ID: 3a37a0ecfd46
Revises: 9153f5449d78
Create Date: 2024-12-24 22:40:23.441152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a37a0ecfd46'
down_revision = '9153f5449d78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_relation_tags_articles',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['service_articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['service_tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'article_id')
    )
    op.drop_index('idx_article_tags_gin', table_name='service_articles', postgresql_using='gin')
    op.drop_column('service_articles', 'tags')
    op.drop_column('service_tags', 'created')
    op.drop_column('service_tags', 'updated')
    op.drop_column('service_tags', 'content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tags', sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('service_tags', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('service_tags', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('service_articles', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.create_index('idx_article_tags_gin', 'service_articles', ['tags'], unique=False, postgresql_using='gin')
    op.drop_table('service_relation_tags_articles')
    # ### end Alembic commands ###
