"""Added slug to the article

Revision ID: 7a805de5e5d8
Revises: ccfd2d8537db
Create Date: 2024-10-31 11:24:51.650138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a805de5e5d8'
down_revision = 'ccfd2d8537db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_articles', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_service_articles_slug'), 'service_articles', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_articles_slug'), table_name='service_articles')
    op.drop_column('service_articles', 'slug')
    # ### end Alembic commands ###
