"""Added read model

Revision ID: 156be20e7fb4
Revises: 7c68bcc6ca7b
Create Date: 2024-06-07 16:53:36.182399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156be20e7fb4'
down_revision = '7c68bcc6ca7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_read',
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=False),
    sa.Column('volumes', sa.Integer(), nullable=False),
    sa.Column('rereads', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_read')
    # ### end Alembic commands ###
