"""Added deleted field to anime

Revision ID: 36a43fc1f0d7
Revises: 47b1673a82ea
Create Date: 2024-05-20 17:46:00.418870

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36a43fc1f0d7"
down_revision = "47b1673a82ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_anime",
        sa.Column(
            "deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_anime", "deleted")
    # ### end Alembic commands ###
