"""Added Article model

Revision ID: 267f088a8828
Revises: b38d06d1364e
Create Date: 2024-10-19 16:02:58.513101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267f088a8828'
down_revision = 'b38d06d1364e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
