"""Added deleted fields

Revision ID: bf31e8e30ed4
Revises: 36a43fc1f0d7
Create Date: 2024-05-21 02:14:35.958483

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bf31e8e30ed4"
down_revision = "36a43fc1f0d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_comments",
        sa.Column(
            "deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "service_favourite",
        sa.Column(
            "deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "service_watch",
        sa.Column(
            "deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_watch", "deleted")
    op.drop_column("service_favourite", "deleted")
    op.drop_column("service_comments", "deleted")
    # ### end Alembic commands ###
