"""Added used field to image

Revision ID: cdb9b148e545
Revises: 57f348c5c8f8
Create Date: 2024-12-23 00:08:15.121780

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdb9b148e545"
down_revision = "57f348c5c8f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_images",
        sa.Column(
            "used",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_images", "used")
    # ### end Alembic commands ###
