"""Added Article model

Revision ID: ccfd2d8537db
Revises: b38d06d1364e
Create Date: 2024-10-30 23:37:56.044416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccfd2d8537db'
down_revision = 'b38d06d1364e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_articles',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('vote_score', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('cover_image_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['service_users.id'], ),
    sa.ForeignKeyConstraint(['cover_image_id'], ['service_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_articles_category'), 'service_articles', ['category'], unique=False)
    op.create_index(op.f('ix_service_articles_cover_image_id'), 'service_articles', ['cover_image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_articles_cover_image_id'), table_name='service_articles')
    op.drop_index(op.f('ix_service_articles_category'), table_name='service_articles')
    op.drop_table('service_articles')
    # ### end Alembic commands ###
