"""Added franchise relation to manga

Revision ID: 2dbc8e451a4f
Revises: bccaf8250166
Create Date: 2024-06-05 17:58:30.188624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbc8e451a4f'
down_revision = 'bccaf8250166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_manga', sa.Column('franchise_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_service_content_manga_franchise_id'), 'service_content_manga', ['franchise_id'], unique=False)
    op.create_foreign_key(None, 'service_content_manga', 'service_content_franchises', ['franchise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_content_manga', type_='foreignkey')
    op.drop_index(op.f('ix_service_content_manga_franchise_id'), table_name='service_content_manga')
    op.drop_column('service_content_manga', 'franchise_id')
    # ### end Alembic commands ###
