"""Removed title size for manga

Revision ID: b374f1f0de11
Revises: 0fa4c5e9a39b
Create Date: 2024-06-01 22:45:44.425994

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b374f1f0de11"
down_revision = "0fa4c5e9a39b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_content_manga",
        "title_original",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(),
    )
    op.alter_column(
        "service_content_manga",
        "title_en",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(),
    )
    op.alter_column(
        "service_content_manga",
        "title_ua",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_content_manga",
        "title_original",
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=255),
    )
    op.alter_column(
        "service_content_manga",
        "title_en",
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=255),
    )
    op.alter_column(
        "service_content_manga",
        "title_ua",
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=255),
    )
    # ### end Alembic commands ###
