"""Add client "verified" field

Revision ID: a4d5b6174fb1
Revises: 96c0d6b7aeba
Create Date: 2024-08-07 01:16:44.543914

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4d5b6174fb1"
down_revision = "96c0d6b7aeba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_clients",
        sa.Column(
            "verified", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_clients", "verified")
    # ### end Alembic commands ###
