"""Added system field to image

Revision ID: 205110e412cf
Revises: 54d3e3969bf8
Create Date: 2025-01-03 23:51:19.579354

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "205110e412cf"
down_revision = "54d3e3969bf8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_images",
        sa.Column(
            "system",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_images", "system")
    # ### end Alembic commands ###
