"""Ported fields from upload to image

Revision ID: 54d3e3969bf8
Revises: 34ca4dae02a2
Create Date: 2025-01-03 23:30:05.788822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d3e3969bf8'
down_revision = '34ca4dae02a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_images', sa.Column('type', sa.String(length=32), nullable=True))
    op.add_column('service_images', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('service_images', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('service_images', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'service_images', 'service_users', ['user_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_images', type_='foreignkey')
    op.drop_column('service_images', 'user_id')
    op.drop_column('service_images', 'size')
    op.drop_column('service_images', 'mime_type')
    op.drop_column('service_images', 'type')
    # ### end Alembic commands ###
