"""Removed uploads model

Revision ID: 75b5d1bb8ae0
Revises: 205110e412cf
Create Date: 2025-01-04 10:54:49.903917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75b5d1bb8ae0'
down_revision = '205110e412cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_uploads_image_id', table_name='service_uploads')
    op.drop_index('ix_service_uploads_path', table_name='service_uploads')
    op.drop_table('service_uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_uploads',
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], name='service_uploads_image_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], name='service_uploads_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_uploads_pkey')
    )
    op.create_index('ix_service_uploads_path', 'service_uploads', ['path'], unique=False)
    op.create_index('ix_service_uploads_image_id', 'service_uploads', ['image_id'], unique=False)
    # ### end Alembic commands ###
