"""Added width/height to image

Revision ID: f5d2a64bc405
Revises: 3b5f5b8a0786
Create Date: 2025-03-02 15:49:42.530951

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5d2a64bc405"
down_revision = "3b5f5b8a0786"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_images",
        sa.Column("height", sa.Integer(), nullable=True, server_default=None),
    )
    op.add_column(
        "service_images",
        sa.Column("width", sa.Integer(), nullable=True, server_default=None),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_images", "width")
    op.drop_column("service_images", "height")
    # ### end Alembic commands ###
