"""Add user_id index to Vote and collection_id index to CollectionContent

Revision ID: 4e66b910a9d7
Revises: d84c7bea1da0
Create Date: 2025-06-29 18:12:31.373191

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "4e66b910a9d7"
down_revision = "d84c7bea1da0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_service_collection_content_collection_id"),
        "service_collection_content",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_votes_user_id"),
        "service_votes",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_votes_user_id"), table_name="service_votes")
    op.drop_index(
        op.f("ix_service_collection_content_collection_id"),
        table_name="service_collection_content",
    )
    # ### end Alembic commands ###
