"""Added back characters count field with correct type

Revision ID: bfe7ae663629
Revises: e809c158c0b5
Create Date: 2025-02-27 15:06:22.904694

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bfe7ae663629"
down_revision = "e809c158c0b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_people",
        sa.Column(
            "characters_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_people", "characters_count")
    # ### end Alembic commands ###
