"""Added missing comment fields to person and character

Revision ID: 95acbb0bd9ea
Revises: e12551343732
Create Date: 2025-09-06 18:56:04.821742

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95acbb0bd9ea"
down_revision = "e12551343732"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_characters",
        sa.Column(
            "comments_count_pagination",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "service_content_characters",
        sa.Column(
            "comments_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_people",
        sa.Column(
            "comments_count_pagination",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "service_content_people",
        sa.Column(
            "comments_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_people", "comments_count")
    op.drop_column("service_content_people", "comments_count_pagination")
    op.drop_column("service_content_characters", "comments_count")
    op.drop_column("service_content_characters", "comments_count_pagination")
    # ### end Alembic commands ###
