"""Added artifact model

Revision ID: 2cea3f324752
Revises: db7db52dbc81
Create Date: 2025-12-17 12:30:52.857372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cea3f324752'
down_revision = 'db7db52dbc81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_artifacts',
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_artifact_lookup', 'service_artifacts', ['user_id', 'name'], unique=True)
    op.create_index(op.f('ix_service_artifacts_name'), 'service_artifacts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_artifacts_name'), table_name='service_artifacts')
    op.drop_index('idx_user_artifact_lookup', table_name='service_artifacts')
    op.drop_table('service_artifacts')
    # ### end Alembic commands ###
