"""Added native score to manga and novel

Revision ID: e12551343732
Revises: 91c20c8fffc4
Create Date: 2025-08-17 17:30:45.250612

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e12551343732"
down_revision = "91c20c8fffc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_manga",
        sa.Column(
            "native_scored_by", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_manga",
        sa.Column(
            "native_score", sa.Float(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_novel",
        sa.Column(
            "native_scored_by", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_novel",
        sa.Column(
            "native_score", sa.Float(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_novel", "native_score")
    op.drop_column("service_content_novel", "native_scored_by")
    op.drop_column("service_content_manga", "native_score")
    op.drop_column("service_content_manga", "native_scored_by")
    # ### end Alembic commands ###
