"""Removed cover fields

Revision ID: 34ca4dae02a2
Revises: ccca6c061336
Create Date: 2025-01-03 22:17:28.859125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ca4dae02a2'
down_revision = 'ccca6c061336'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_articles_cover_image_id', table_name='service_articles')
    op.drop_constraint('service_articles_cover_image_id_fkey', 'service_articles', type_='foreignkey')
    op.drop_column('service_articles', 'cover_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_articles', sa.Column('cover_image_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('service_articles_cover_image_id_fkey', 'service_articles', 'service_images', ['cover_image_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_service_articles_cover_image_id', 'service_articles', ['cover_image_id'], unique=False)
    # ### end Alembic commands ###
