"""Add lower(username) index on the User model

Revision ID: d84c7bea1da0
Revises: d8a764054cd3
Create Date: 2025-06-29 17:41:00.974894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84c7bea1da0'
down_revision = 'd8a764054cd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lower_username', 'service_users', [sa.text('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lower_username', table_name='service_users')
    # ### end Alembic commands ###
