"""Removed text from article

Revision ID: 198605b6007f
Revises: e2fe89547055
Create Date: 2025-01-03 00:54:58.316896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198605b6007f'
down_revision = 'e2fe89547055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_articles', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_articles', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
