"""Removed bad field

Revision ID: e809c158c0b5
Revises: f4f7dd2ef3e4
Create Date: 2025-02-27 15:05:24.611836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e809c158c0b5'
down_revision = 'f4f7dd2ef3e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_people', 'characters_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_people', sa.Column('characters_count', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
