"""Added count fields for person

Revision ID: d593c0a05b45
Revises: 2cb6731d1b5a
Create Date: 2025-02-24 22:44:06.096522

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d593c0a05b45"
down_revision = "2cb6731d1b5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_people",
        sa.Column(
            "characters_count", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_people",
        sa.Column(
            "anime_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_people", "anime_count")
    op.drop_column("service_content_people", "characters_count")
    # ### end Alembic commands ###
