"""One more field for person

Revision ID: 27946d7affb5
Revises: d593c0a05b45
Create Date: 2025-02-24 22:45:17.157151

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27946d7affb5"
down_revision = "d593c0a05b45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_people",
        sa.Column(
            "needs_count_update",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_people", "needs_count_update")
    # ### end Alembic commands ###
