"""Add latest comments partial index

Revision ID: 6ae6fd452211
Revises: 4e66b910a9d7
Create Date: 2025-06-30 00:27:17.540210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae6fd452211'
down_revision = '4e66b910a9d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_latest', 'service_comments', [sa.text('created DESC')], unique=False, postgresql_where=sa.text('nlevel(path) = 1 AND hidden = false AND private = false AND deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_latest', table_name='service_comments', postgresql_where=sa.text('nlevel(path) = 1 AND hidden = false AND private = false AND deleted = false'))
    # ### end Alembic commands ###
