"""Even more fields for person

Revision ID: 9a9d7c8b946d
Revises: 27946d7affb5
Create Date: 2025-02-24 22:54:25.904485

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a9d7c8b946d"
down_revision = "27946d7affb5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_people",
        sa.Column(
            "manga_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_people",
        sa.Column(
            "novel_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_people", "novel_count")
    op.drop_column("service_content_people", "manga_count")
    # ### end Alembic commands ###
