"""Added content preview to edit

Revision ID: c0bf2654080f
Revises: 95acbb0bd9ea
Create Date: 2025-10-17 17:59:08.427454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0bf2654080f'
down_revision = '95acbb0bd9ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_edits', sa.Column('content_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}",))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_edits', 'content_preview')
    # ### end Alembic commands ###
