"""Added new_email field to user

Revision ID: ea1308f17d67
Revises: d8234d16569f
Create Date: 2025-11-16 10:10:50.731730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1308f17d67'
down_revision = 'd8234d16569f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_users', sa.Column('new_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_service_users_new_email'), 'service_users', ['new_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_users_new_email'), table_name='service_users')
    op.drop_column('service_users', 'new_email')
    # ### end Alembic commands ###
