"""Added novel_count to character model

Revision ID: 2cb6731d1b5a
Revises: 38645366d101
Create Date: 2025-02-24 22:19:37.444241

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cb6731d1b5a"
down_revision = "38645366d101"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_characters",
        sa.Column(
            "novel_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_characters", "novel_count")
    # ### end Alembic commands ###
