"""Added private field to artifact

Revision ID: e67c51841277
Revises: 2cea3f324752
Create Date: 2025-12-21 00:50:16.237181

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e67c51841277"
down_revision = "2cea3f324752"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_artifacts",
        sa.Column(
            "private", sa.Boolean(), nullable=False, server_default="true"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_artifacts", "private")
    # ### end Alembic commands ###
