"""Added voices_count and anime_count to character model

Revision ID: f5423a222e1a
Revises: c6c1c2bef454
Create Date: 2025-02-24 20:33:13.751500

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5423a222e1a"
down_revision = "c6c1c2bef454"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_characters",
        sa.Column(
            "voices_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_characters",
        sa.Column(
            "anime_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_characters", "anime_count")
    op.drop_column("service_content_characters", "voices_count")
    # ### end Alembic commands ###
