"""Added preview to article

Revision ID: d8234d16569f
Revises: c0bf2654080f
Create Date: 2025-11-10 11:30:11.944735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8234d16569f'
down_revision = 'c0bf2654080f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_articles', sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_articles', 'preview')
    # ### end Alembic commands ###
