"""Add index to user_id in history

Revision ID: 36789da11850
Revises: 7ec68ab99745
Create Date: 2025-06-29 11:22:39.349397

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "36789da11850"
down_revision = "7ec68ab99745"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_service_user_history_user_id"),
        "service_user_history",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_service_user_history_user_id"),
        table_name="service_user_history",
    )
    # ### end Alembic commands ###
