"""Added native score to anime

Revision ID: 91c20c8fffc4
Revises: a809916a7b32
Create Date: 2025-08-17 12:47:42.324875

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "91c20c8fffc4"
down_revision = "a809916a7b32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_anime",
        sa.Column(
            "native_scored_by", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_content_anime",
        sa.Column(
            "native_score", sa.Float(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_anime", "native_score")
    op.drop_column("service_content_anime", "native_scored_by")
    # ### end Alembic commands ###
