"""Added customization fields

Revision ID: db7db52dbc81
Revises: ea1308f17d67
Create Date: 2025-12-15 13:27:48.766458

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import json

# revision identifiers, used by Alembic.
revision = "db7db52dbc81"
down_revision = "ea1308f17d67"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_users",
        sa.Column(
            "styles",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(
                f"""'{
                    json.dumps(
                        {
                            "light": {
                                "colors": {
                                    "background": None,
                                    "foreground": None,
                                    "primary": None,
                                    "primary_foreground": None,
                                    "primary_border": None,
                                    "secondary": None,
                                    "secondary_foreground": None,
                                    "muted": None,
                                    "muted_foreground": None,
                                    "accent_foreground": None,
                                    "border": None,
                                    "ring": None,
                                    "popover": None,
                                    "popover_foreground": None,
                                    "sidebar_background": None,
                                    "sidebar_foreground": None,
                                    "sidebar_primary": None,
                                    "sidebar_primary_foreground": None,
                                    "sidebar_accent": None,
                                    "sidebar_accent_foreground": None,
                                    "sidebar_border": None,
                                    "sidebar_ring": None,
                                },
                            },
                            "dark": {
                                "colors": {
                                    "background": None,
                                    "foreground": None,
                                    "primary": None,
                                    "primary_foreground": None,
                                    "primary_border": None,
                                    "secondary": None,
                                    "secondary_foreground": None,
                                    "muted": None,
                                    "muted_foreground": None,
                                    "accent_foreground": None,
                                    "border": None,
                                    "ring": None,
                                    "popover": None,
                                    "popover_foreground": None,
                                    "sidebar_background": None,
                                    "sidebar_foreground": None,
                                    "sidebar_primary": None,
                                    "sidebar_primary_foreground": None,
                                    "sidebar_accent": None,
                                    "sidebar_accent_foreground": None,
                                    "sidebar_border": None,
                                    "sidebar_ring": None,
                                },
                                "body": {
                                    "background_image": None,
                                },
                            },
                            "radius": None,
                            "typography": {
                                "h1": None,
                                "h2": None,
                                "h3": None,
                                "h4": None,
                                "h5": None,
                                "p": None,
                            },
                        }
                    )
                }'::jsonb"""
            ),
        ),
    )

    op.add_column(
        "service_users",
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(
                f"""'{
                    json.dumps(
                        {
                            "title_language": None,
                            "name_language": None,
                            "effects": None,
                        }
                    )
                }'::jsonb"""
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_users", "preferences")
    op.drop_column("service_users", "styles")
    # ### end Alembic commands ###
