"""Changes to user article stats

Revision ID: 7bd64948248e
Revises: 0ef0cad343d6
Create Date: 2025-01-01 20:39:05.930603

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bd64948248e"
down_revision = "0ef0cad343d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_stats_articles",
        sa.Column("total", sa.Integer(), nullable=False, server_default="0"),
    )
    op.drop_column("service_stats_articles", "reviews")
    op.drop_column("service_stats_articles", "news")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_stats_articles",
        sa.Column("news", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "service_stats_articles",
        sa.Column("reviews", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("service_stats_articles", "total")
    # ### end Alembic commands ###
