"""Added index to deleted field

Revision ID: 80a4c31dfa1e
Revises: 5c3882d4210c
Create Date: 2025-02-24 21:34:11.840374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a4c31dfa1e'
down_revision = '5c3882d4210c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_service_articles_deleted'), 'service_articles', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_collections_deleted'), 'service_collections', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_comments_deleted'), 'service_comments', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_content_anime_deleted'), 'service_content_anime', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_content_manga_deleted'), 'service_content_manga', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_content_novel_deleted'), 'service_content_novel', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_favourite_deleted'), 'service_favourite', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_read_deleted'), 'service_read', ['deleted'], unique=False)
    op.create_index(op.f('ix_service_watch_deleted'), 'service_watch', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_watch_deleted'), table_name='service_watch')
    op.drop_index(op.f('ix_service_read_deleted'), table_name='service_read')
    op.drop_index(op.f('ix_service_favourite_deleted'), table_name='service_favourite')
    op.drop_index(op.f('ix_service_content_novel_deleted'), table_name='service_content_novel')
    op.drop_index(op.f('ix_service_content_manga_deleted'), table_name='service_content_manga')
    op.drop_index(op.f('ix_service_content_anime_deleted'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_comments_deleted'), table_name='service_comments')
    op.drop_index(op.f('ix_service_collections_deleted'), table_name='service_collections')
    op.drop_index(op.f('ix_service_articles_deleted'), table_name='service_articles')
    # ### end Alembic commands ###
