"""Added attachment fields to image

Revision ID: d1aa42757f69
Revises: 75b5d1bb8ae0
Create Date: 2025-01-09 12:12:47.599773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aa42757f69'
down_revision = '75b5d1bb8ae0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_images', sa.Column('attachment_content_type', sa.String(), nullable=True))
    op.add_column('service_images', sa.Column('attachment_content_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_service_images_attachment_content_id'), 'service_images', ['attachment_content_id'], unique=False)
    op.create_index(op.f('ix_service_images_attachment_content_type'), 'service_images', ['attachment_content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_images_attachment_content_type'), table_name='service_images')
    op.drop_index(op.f('ix_service_images_attachment_content_id'), table_name='service_images')
    op.drop_column('service_images', 'attachment_content_id')
    op.drop_column('service_images', 'attachment_content_type')
    # ### end Alembic commands ###
