"""Add index to user_id in notifications

Revision ID: 7ec68ab99745
Revises: 8a9077498cf4
Create Date: 2025-06-29 00:30:46.498236

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "7ec68ab99745"
down_revision = "8a9077498cf4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_service_notifications_user_id"),
        "service_notifications",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_service_notifications_user_id"),
        table_name="service_notifications",
    )
    # ### end Alembic commands ###
