"""Better fields for user article stats

Revision ID: 3b5f5b8a0786
Revises: bfe7ae663629
Create Date: 2025-02-28 20:47:58.527161

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b5f5b8a0786"
down_revision = "bfe7ae663629"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_stats_articles",
        sa.Column(
            "total_articles", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_stats_articles",
        sa.Column(
            "total_comments", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_stats_articles",
        sa.Column(
            "author_score", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "service_stats_articles",
        sa.Column(
            "total_likes", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.drop_column("service_stats_articles", "total")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_stats_articles",
        sa.Column(
            "total",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("service_stats_articles", "total_likes")
    op.drop_column("service_stats_articles", "author_score")
    op.drop_column("service_stats_articles", "total_comments")
    op.drop_column("service_stats_articles", "total_articles")
    # ### end Alembic commands ###
