"""Removed category from article tag

Revision ID: a34dd7174d66
Revises: f5d2a64bc405
Create Date: 2025-03-02 20:06:46.101888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34dd7174d66'
down_revision = 'f5d2a64bc405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_tags_category', table_name='service_tags')
    op.drop_column('service_tags', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tags', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_service_tags_category', 'service_tags', ['category'], unique=False)
    # ### end Alembic commands ###
