"""Add latest comments partial index

Revision ID: a809916a7b32
Revises: 4e66b910a9d7
Create Date: 2025-06-30 01:03:32.470290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a809916a7b32'
down_revision = '4e66b910a9d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_comment_latest', 'service_comments', [sa.text('created DESC')], unique=False, postgresql_where=sa.text('nlevel(path) = 1 AND NOT hidden AND NOT private AND NOT deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_latest', table_name='service_comments', postgresql_where=sa.text('nlevel(path) = 1 AND NOT hidden AND NOT private AND NOT deleted'))
    # ### end Alembic commands ###
