"""Add index to user_id in anime watch and manga/novel read

Revision ID: d8a764054cd3
Revises: 36789da11850
Create Date: 2025-06-29 12:15:23.865468

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "d8a764054cd3"
down_revision = "36789da11850"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_service_read_user_id"),
        "service_read",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_watch_user_id"),
        "service_watch",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_watch_user_id"), table_name="service_watch")
    op.drop_index(op.f("ix_service_read_user_id"), table_name="service_read")
    # ### end Alembic commands ###
