"""Added needs_count_update to character model

Revision ID: 5c3882d4210c
Revises: f5423a222e1a
Create Date: 2025-02-24 20:39:36.055564

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c3882d4210c"
down_revision = "f5423a222e1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_characters",
        sa.Column(
            "needs_count_update",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_characters", "needs_count_update")
    # ### end Alembic commands ###
