"""add needs_search_update column to article

Revision ID: 8818ea87e8cf
Revises: 0dc2df191429
Create Date: 2026-03-09 14:56:35.409402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8818ea87e8cf'
down_revision = '0dc2df191429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_articles', sa.Column('needs_search_update', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_articles', 'needs_search_update')
    # ### end Alembic commands ###
