"""Removed activity model

Revision ID: 9ed1ab5095a8
Revises: 3e8cf3454c39
Create Date: 2026-03-30 00:06:27.033016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ed1ab5095a8'
down_revision = '3e8cf3454c39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_user_activity_interval', table_name='service_user_activity')
    op.drop_index('ix_service_user_activity_timestamp', table_name='service_user_activity')
    op.drop_table('service_user_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_user_activity',
    sa.Column('used_logs', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('actions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], name='service_user_activity_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_user_activity_pkey')
    )
    op.create_index('ix_service_user_activity_timestamp', 'service_user_activity', ['timestamp'], unique=False)
    op.create_index('ix_service_user_activity_interval', 'service_user_activity', ['interval'], unique=False)
    # ### end Alembic commands ###
