"""Added created field to anime/manga/novel

Revision ID: 0dc2df191429
Revises: e67c51841277
Create Date: 2026-01-22 21:06:57.199867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc2df191429'
down_revision = 'e67c51841277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('service_content_manga', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('service_content_novel', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_novel', 'created')
    op.drop_column('service_content_manga', 'created')
    op.drop_column('service_content_anime', 'created')
    # ### end Alembic commands ###
