"""Added orphan field to character

Revision ID: 685836147116
Revises: e87a45d84be9
Create Date: 2026-06-30 20:44:43.796314

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "685836147116"
down_revision = "e87a45d84be9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_characters",
        sa.Column(
            "orphan", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_characters", "orphan")
    # ### end Alembic commands ###
