"""Added author_id to feed model

Revision ID: ec958c1bfac9
Revises: f5c9d858fc15
Create Date: 2026-03-08 17:32:24.066990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec958c1bfac9'
down_revision = 'f5c9d858fc15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_feed', sa.Column('author_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'service_feed', 'service_users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_feed', type_='foreignkey')
    op.drop_column('service_feed', 'author_id')
    # ### end Alembic commands ###
