"""Added title_native fields

Revision ID: b5cc5de79d66
Revises: 3778d7981774
Create Date: 2026-09-27 00:26:19.030773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cc5de79d66'
down_revision = '3778d7981774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime', sa.Column('title_native', sa.String(length=255), nullable=True))
    op.add_column('service_content_manga', sa.Column('title_native', sa.String(length=255), nullable=True))
    op.add_column('service_content_novel', sa.Column('title_native', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_novel', 'title_native')
    op.drop_column('service_content_manga', 'title_native')
    op.drop_column('service_content_anime', 'title_native')
    # ### end Alembic commands ###
