"""Added search fields to article

Revision ID: 3e8cf3454c39
Revises: dff9408f59e9
Create Date: 2026-03-15 18:31:45.310207

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e8cf3454c39"
down_revision = "dff9408f59e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_articles",
        sa.Column(
            "needs_search_update",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_articles", "needs_search_update")
    # ### end Alembic commands ###
