"""Added score field to review

Revision ID: 80af30ce258a
Revises: 215a8952600b
Create Date: 2026-07-08 23:07:02.153847

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80af30ce258a"
down_revision = "215a8952600b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_reviews",
        sa.Column("score", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_reviews", "score")
    # ### end Alembic commands ###
