"""Added filter fields to feed

Revision ID: c84883e875cf
Revises: 37a3fd299059
Create Date: 2026-04-03 12:00:05.496576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84883e875cf'
down_revision = '37a3fd299059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_feed', sa.Column('filter_content_type', sa.String(), nullable=True))
    op.add_column('service_feed', sa.Column('filter_category', sa.String(), nullable=True))
    op.create_index(op.f('ix_service_feed_filter_category'), 'service_feed', ['filter_category'], unique=False)
    op.create_index(op.f('ix_service_feed_filter_content_type'), 'service_feed', ['filter_content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_feed_filter_content_type'), table_name='service_feed')
    op.drop_index(op.f('ix_service_feed_filter_category'), table_name='service_feed')
    op.drop_column('service_feed', 'filter_category')
    op.drop_column('service_feed', 'filter_content_type')
    # ### end Alembic commands ###
