"""Added index to deleted

Revision ID: dff9408f59e9
Revises: 860b5b40b8a3
Create Date: 2026-03-08 18:40:08.035651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff9408f59e9'
down_revision = '860b5b40b8a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_service_feed_deleted'), 'service_feed', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_feed_deleted'), table_name='service_feed')
    # ### end Alembic commands ###
