"""Added start/end date to watch

Revision ID: 378544676641
Revises: c65a6601e192
Create Date: 2026-02-08 18:55:21.794856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378544676641'
down_revision = 'c65a6601e192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_watch', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('service_watch', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_watch', 'end_date')
    op.drop_column('service_watch', 'start_date')
    # ### end Alembic commands ###
