"""Added index for feed

Revision ID: ec3418faf1a0
Revises: ec958c1bfac9
Create Date: 2026-03-08 17:48:57.456956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3418faf1a0'
down_revision = 'ec958c1bfac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_feed_content', 'service_feed', ['content_type', 'content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feed_content', table_name='service_feed')
    # ### end Alembic commands ###
