"""Added total_replies to comment

Revision ID: 37a3fd299059
Revises: 9ed1ab5095a8
Create Date: 2026-04-03 00:09:48.994278

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37a3fd299059"
down_revision = "9ed1ab5095a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_comments",
        sa.Column(
            "total_replies", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_comments", "total_replies")
    # ### end Alembic commands ###
