"""Added start/end date to read

Revision ID: 3142eb9f93b3
Revises: 378544676641
Create Date: 2026-02-12 15:00:33.615616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3142eb9f93b3'
down_revision = '378544676641'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_read', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('service_read', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_read', 'end_date')
    op.drop_column('service_read', 'start_date')
    # ### end Alembic commands ###
