"""Added search field to collection

Revision ID: 2d4fd1b3db1b
Revises: a3f21c9d47be
Create Date: 2026-09-19 17:26:12.892060

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d4fd1b3db1b"
down_revision = "a3f21c9d47be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_collections",
        sa.Column(
            "needs_search_update",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_collections", "needs_search_update")
    # ### end Alembic commands ###
