"""Added relations field to franchise

Revision ID: 93ce5aa3766f
Revises: b5cc5de79d66
Create Date: 2026-10-04 16:48:33.230246

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "93ce5aa3766f"
down_revision = "b5cc5de79d66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_franchises",
        sa.Column(
            "relations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_franchises", "relations")
    # ### end Alembic commands ###
