"""Fixed index name

Revision ID: c65a6601e192
Revises: 4118892f8a06
Create Date: 2026-02-08 17:33:57.783384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65a6601e192'
down_revision = '4118892f8a06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_artifact_lookup', table_name='service_digests')
    op.drop_index('ix_service_artifacts_name', table_name='service_digests')
    op.create_index('idx_user_digest_lookup', 'service_digests', ['user_id', 'name'], unique=True)
    op.create_index(op.f('ix_service_digests_name'), 'service_digests', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_digests_name'), table_name='service_digests')
    op.drop_index('idx_user_digest_lookup', table_name='service_digests')
    op.create_index('ix_service_artifacts_name', 'service_digests', ['name'], unique=False)
    op.create_index('idx_user_artifact_lookup', 'service_digests', ['user_id', 'name'], unique=True)
    # ### end Alembic commands ###
