"""Addew review model

Revision ID: e87a45d84be9
Revises: c84883e875cf
Create Date: 2026-06-04 00:19:48.791717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87a45d84be9'
down_revision = 'c84883e875cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_reviews',
    sa.Column('recommended', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['service_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_reviews_recommended'), 'service_reviews', ['recommended'], unique=False)
    op.create_index(op.f('ix_service_reviews_user_id'), 'service_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_reviews_user_id'), table_name='service_reviews')
    op.drop_index(op.f('ix_service_reviews_recommended'), table_name='service_reviews')
    op.drop_table('service_reviews')
    # ### end Alembic commands ###
