"""Added rewatches to AnimeWatch

Revision ID: 22ac5926f9b2
Revises: a35b01e181b2
Create Date: 2024-01-19 00:04:34.577710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "22ac5926f9b2"
down_revision = "a35b01e181b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_watch",
        sa.Column(
            "rewatches", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_watch", "rewatches")
    # ### end Alembic commands ###
