"""Edits

Revision ID: 36b994f3335a
Revises: e710ade04f46
Create Date: 2023-11-08 20:17:22.381996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36b994f3335a'
down_revision = 'e710ade04f46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_edits',
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('edit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('moderator_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['service_users.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('edit_id', 'id')
    )
    op.create_index(op.f('ix_service_edits_edit_id'), 'service_edits', ['edit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_edits_edit_id'), table_name='service_edits')
    op.drop_table('service_edits')
    # ### end Alembic commands ###
