"""Removed updated field from collection content

Revision ID: 3da0988d8d0b
Revises: 9ed39a60e42b
Create Date: 2024-02-23 14:24:42.319402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3da0988d8d0b'
down_revision = '9ed39a60e42b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_collection_content', 'updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_collection_content', sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
