"""Added visibility field to collection

Revision ID: 3f6359705077
Revises: 8e997ebbcbed
Create Date: 2024-03-20 19:28:11.291965

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f6359705077"
down_revision = "8e997ebbcbed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_collections",
        sa.Column(
            "visibility",
            sa.String(length=16),
            server_default="public",
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_service_collections_visibility"),
        "service_collections",
        ["visibility"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_service_collections_visibility"),
        table_name="service_collections",
    )
    op.drop_column("service_collections", "visibility")
    # ### end Alembic commands ###
