"""Added collection models

Revision ID: 49691627cab8
Revises: 01600fd4bd86
Create Date: 2024-02-21 00:09:23.186957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49691627cab8'
down_revision = '01600fd4bd86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_collections',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_collection_groups',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['service_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_collection_groups')
    op.drop_table('service_collections')
    # ### end Alembic commands ###
