"""Addeded description to character model

Revision ID: 4bc89139bee2
Revises: 8207423b9bc0
Create Date: 2024-02-02 00:44:42.825026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc89139bee2'
down_revision = '8207423b9bc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_characters', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_characters', 'description')
    # ### end Alembic commands ###
