"""Addeded score field to comment

Revision ID: 4fc436e61273
Revises: 04a78ebfda3d
Create Date: 2024-01-28 23:27:15.579076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4fc436e61273"
down_revision = "04a78ebfda3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_comments",
        sa.Column("score", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_comments", "score")
    # ### end Alembic commands ###
