"""Added cover image to user

Revision ID: 514751336814
Revises: 22ac5926f9b2
Create Date: 2024-01-22 23:43:21.103509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514751336814'
down_revision = '22ac5926f9b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_users', sa.Column('cover_image_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_service_users_cover_image_id'), 'service_users', ['cover_image_id'], unique=False)
    op.create_foreign_key(None, 'service_users', 'service_images', ['cover_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_users', type_='foreignkey')
    op.drop_index(op.f('ix_service_users_cover_image_id'), table_name='service_users')
    op.drop_column('service_users', 'cover_image_id')
    # ### end Alembic commands ###
