"""Added nsfw field to anime

Revision ID: 52ea03a243cd
Revises: 5c392699eeae
Create Date: 2023-05-19 21:39:46.733951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52ea03a243cd"
down_revision = "5c392699eeae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_content_anime", sa.Column("nsfw", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_content_anime", "nsfw")
    # ### end Alembic commands ###
