"""Initial migration

Revision ID: 5c392699eeae
Revises: 
Create Date: 2023-05-19 21:36:07.490947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c392699eeae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'service_relation_anime_genres', 'service_content_anime', ['anime_id'], ['id'])
    op.create_foreign_key(None, 'service_relation_anime_genres', 'service_content_anime_genres', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'service_relation_anime_producers', 'service_content_companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'service_relation_anime_producers', 'service_content_anime', ['anime_id'], ['id'])
    op.create_foreign_key(None, 'service_relation_anime_studios', 'service_content_anime', ['anime_id'], ['id'])
    op.create_foreign_key(None, 'service_relation_anime_studios', 'service_content_companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_relation_anime_studios', type_='foreignkey')
    op.drop_constraint(None, 'service_relation_anime_studios', type_='foreignkey')
    op.drop_constraint(None, 'service_relation_anime_producers', type_='foreignkey')
    op.drop_constraint(None, 'service_relation_anime_producers', type_='foreignkey')
    op.drop_constraint(None, 'service_relation_anime_genres', type_='foreignkey')
    op.drop_constraint(None, 'service_relation_anime_genres', type_='foreignkey')
    # ### end Alembic commands ###
