"""Added ignored_notifications field to user

Revision ID: 5f0b8e0c784c
Revises: a48975336cef
Create Date: 2024-04-07 22:58:21.043230

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f0b8e0c784c"
down_revision = "a48975336cef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_users",
        sa.Column(
            "ignored_notifications",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_users", "ignored_notifications")
    # ### end Alembic commands ###
