"""Added image

Revision ID: 62721f475ed7
Revises: 52ea03a243cd
Create Date: 2023-05-29 13:33:03.126796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62721f475ed7'
down_revision = '52ea03a243cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime', sa.Column('image_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'service_content_anime', 'service_images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_content_anime', type_='foreignkey')
    op.drop_column('service_content_anime', 'image_id')
    # ### end Alembic commands ###
