"""Unique image path

Revision ID: 725cd4e97eb9
Revises: 62721f475ed7
Create Date: 2023-05-29 13:52:05.789268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725cd4e97eb9'
down_revision = '62721f475ed7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'service_images', ['path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_images', type_='unique')
    # ### end Alembic commands ###
