"""Added weight to staff role

Revision ID: 7b3c9e545ae3
Revises: f1e35aec9d36
Create Date: 2023-12-18 21:32:41.352592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3c9e545ae3'
down_revision = 'f1e35aec9d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime_staff_roles', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_anime_staff_roles', 'weight')
    # ### end Alembic commands ###
