"""Added secret to upload model

Revision ID: 7b61875fad21
Revises: adb9d28335af
Create Date: 2023-12-21 01:20:40.539295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b61875fad21'
down_revision = 'adb9d28335af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_upload_requests', sa.Column('secret', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_service_upload_requests_secret'), 'service_upload_requests', ['secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_upload_requests_secret'), table_name='service_upload_requests')
    op.drop_column('service_upload_requests', 'secret')
    # ### end Alembic commands ###
