"""Addeded activity model (again)

Revision ID: 8207423b9bc0
Revises: 4fc436e61273
Create Date: 2024-02-02 00:33:18.563784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8207423b9bc0'
down_revision = '4fc436e61273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_activity',
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_activity_activity_type'), 'service_activity', ['activity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_activity_activity_type'), table_name='service_activity')
    op.drop_table('service_activity')
    # ### end Alembic commands ###
