"""Addeded activity model

Revision ID: 83dce1c46c9d
Revises: 4fc436e61273
Create Date: 2024-02-01 02:27:16.537928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dce1c46c9d'
down_revision = '4fc436e61273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
