"""Added spoiler and nsfw for collection

Revision ID: 8604811ee56b
Revises: e4fa15bf9fb1
Create Date: 2024-02-23 14:19:51.126320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8604811ee56b'
down_revision = 'e4fa15bf9fb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_collections', sa.Column('spoiler', sa.Boolean(), nullable=False))
    op.add_column('service_collections', sa.Column('nsfw', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_collections', 'nsfw')
    op.drop_column('service_collections', 'spoiler')
    # ### end Alembic commands ###
