"""Added tags field to collection

Revision ID: 977e1c7a1f9a
Revises: fc8d5ad8a8c6
Create Date: 2024-02-24 19:01:16.080840

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "977e1c7a1f9a"
down_revision = "fc8d5ad8a8c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_collections",
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String()),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_collections", "tags")
    # ### end Alembic commands ###
