"""Added mal_id field to anime

Revision ID: 99e4a8aa5bf3
Revises: 1841b8bc0b1b
Create Date: 2023-11-24 21:22:49.447606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e4a8aa5bf3'
down_revision = '1841b8bc0b1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime', sa.Column('mal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_service_content_anime_mal_id'), 'service_content_anime', ['mal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_content_anime_mal_id'), table_name='service_content_anime')
    op.drop_column('service_content_anime', 'mal_id')
    # ### end Alembic commands ###
