"""Added data field to notification

Revision ID: 9dfe86b9e932
Revises: d0add8734e1a
Create Date: 2024-02-11 02:28:50.237985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9dfe86b9e932'
down_revision = 'd0add8734e1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_notifications', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_notifications', 'data')
    # ### end Alembic commands ###
