"""Added system_edit field to edit

Revision ID: a41f1ba390a2
Revises: 700c99947427
Create Date: 2023-12-28 01:41:47.717095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a41f1ba390a2"
down_revision = "700c99947427"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_edits",
        sa.Column(
            "system_edit",
            sa.Boolean(),
            server_default=sa.schema.DefaultClause("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_edits", "system_edit")
    # ### end Alembic commands ###
