"""Addeded score field to comment

Revision ID: a46d72c022c9
Revises: 04a78ebfda3d
Create Date: 2024-01-28 23:22:52.095450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46d72c022c9'
down_revision = '04a78ebfda3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
