"""Upload request model

Revision ID: adb9d28335af
Revises: 7b3c9e545ae3
Create Date: 2023-12-21 01:09:08.941622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb9d28335af'
down_revision = '7b3c9e545ae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_upload_requests',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_upload_requests_image_id'), 'service_upload_requests', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_upload_requests_image_id'), table_name='service_upload_requests')
    op.drop_table('service_upload_requests')
    # ### end Alembic commands ###
