"""Addeded service fields to comment

Revision ID: bc540d13f1d1
Revises: dc741ff7e111
Create Date: 2024-01-28 02:14:55.165529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bc540d13f1d1"
down_revision = "dc741ff7e111"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_comments",
        sa.Column(
            "history",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "service_comments", sa.Column("hidden_by_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "service_comments", "service_users", ["hidden_by_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service_comments", type_="foreignkey")
    op.drop_column("service_comments", "hidden_by_id")
    op.drop_column("service_comments", "history")
    # ### end Alembic commands ###
