"""Removed franchise name

Revision ID: cb015bc23e35
Revises: 476b06e0abb1
Create Date: 2023-05-29 19:45:45.503121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb015bc23e35'
down_revision = '476b06e0abb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_anime_franchises', 'name_ua')
    op.drop_column('service_content_anime_franchises', 'name_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime_franchises', sa.Column('name_en', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('service_content_anime_franchises', sa.Column('name_ua', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
