"""Added hidden field to comment

Revision ID: dc741ff7e111
Revises: 208536a34d07
Create Date: 2024-01-25 14:48:17.253838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc741ff7e111"
down_revision = "208536a34d07"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_comments",
        sa.Column(
            "hidden",
            sa.Boolean(),
            server_default=sa.schema.DefaultClause("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_comments", "hidden")
    # ### end Alembic commands ###
