"""Added content id to franchise

Revision ID: de0ee9afd645
Revises: cb015bc23e35
Create Date: 2023-05-29 21:24:17.888927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0ee9afd645'
down_revision = 'cb015bc23e35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime_franchises', sa.Column('content_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_service_content_anime_franchises_content_id'), 'service_content_anime_franchises', ['content_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_content_anime_franchises_content_id'), table_name='service_content_anime_franchises')
    op.drop_column('service_content_anime_franchises', 'content_id')
    # ### end Alembic commands ###
