"""Replaces groups model with label field

Revision ID: e4fa15bf9fb1
Revises: 9d59170b2da4
Create Date: 2024-02-22 16:04:06.476064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4fa15bf9fb1'
down_revision = '9d59170b2da4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_collection_content',
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['service_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('service_collection_groups')
    op.drop_table('service_collection_group_content')
    op.add_column('service_collections', sa.Column('labels', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_collections', 'labels')
    op.create_table('service_collection_group_content',
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='service_collection_group_content_pkey')
    )
    op.create_table('service_collection_groups',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['service_collections.id'], name='service_collection_groups_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_collection_groups_pkey')
    )
    op.drop_table('service_collection_content')
    # ### end Alembic commands ###
