"""Added aggregator_updated field to anime

Revision ID: e64db5c39606
Revises: a41f1ba390a2
Create Date: 2023-12-28 02:07:22.943530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64db5c39606'
down_revision = 'a41f1ba390a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_content_anime', sa.Column('aggregator_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_content_anime', 'aggregator_updated')
    # ### end Alembic commands ###
