"""Added role to user

Revision ID: e710ade04f46
Revises: 13a8c8325dde
Create Date: 2023-08-24 14:37:24.645189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e710ade04f46"
down_revision = "13a8c8325dde"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_user_oauth",
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("oauth_id", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["service_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "service_content_anime",
        sa.Column(
            "ignored_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    op.add_column(
        "service_users", sa.Column("role", sa.String(length=64), nullable=True)
    )
    op.alter_column(
        "service_users",
        "username",
        existing_type=sa.VARCHAR(length=16),
        nullable=True,
    )
    op.alter_column(
        "service_users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "service_users",
        "password_hash",
        existing_type=sa.VARCHAR(length=60),
        nullable=True,
    )
    op.drop_index("ix_service_users_email", table_name="service_users")
    op.create_index(
        op.f("ix_service_users_email"), "service_users", ["email"], unique=False
    )
    op.drop_index("ix_service_users_username", table_name="service_users")
    op.create_index(
        op.f("ix_service_users_username"),
        "service_users",
        ["username"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_users_role"), "service_users", ["role"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_users_role"), table_name="service_users")
    op.drop_index(op.f("ix_service_users_username"), table_name="service_users")
    op.create_index(
        "ix_service_users_username", "service_users", ["username"], unique=False
    )
    op.drop_index(op.f("ix_service_users_email"), table_name="service_users")
    op.create_index(
        "ix_service_users_email", "service_users", ["email"], unique=False
    )
    op.alter_column(
        "service_users",
        "password_hash",
        existing_type=sa.VARCHAR(length=60),
        nullable=False,
    )
    op.alter_column(
        "service_users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "service_users",
        "username",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
    )
    op.drop_column("service_users", "role")
    op.drop_column("service_content_anime", "ignored_fields")
    op.drop_table("service_user_oauth")
    # ### end Alembic commands ###
