"""Added content_type field to collection

Revision ID: fc8d5ad8a8c6
Revises: 1a409d817c42
Create Date: 2024-02-24 01:13:36.322822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8d5ad8a8c6'
down_revision = '1a409d817c42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_collections', sa.Column('content_type', sa.String(), nullable=False))
    op.create_index(op.f('ix_service_collections_content_type'), 'service_collections', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_collections_content_type'), table_name='service_collections')
    op.drop_column('service_collections', 'content_type')
    # ### end Alembic commands ###
