"""Added deleted field to collection

Revision ID: fcd381ed27d7
Revises: 43418cadd4f4
Create Date: 2024-02-27 16:08:52.669077

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcd381ed27d7"
down_revision = "43418cadd4f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_collections",
        sa.Column(
            "deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_collections", "deleted")
    # ### end Alembic commands ###
