"""Added Upload model

Revision ID: 0d153972952b
Revises: 7b3c9e545ae3
Create Date: 2023-12-21 23:18:58.031407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d153972952b'
down_revision = '7b3c9e545ae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_uploads',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_uploads_image_id'), 'service_uploads', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_uploads_image_id'), table_name='service_uploads')
    op.drop_table('service_uploads')
    # ### end Alembic commands ###
