"""System timestamps

Revision ID: 32046c7c41ff
Revises: fd7ed0458b44
Create Date: 2024-02-08 16:59:45.883363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32046c7c41ff'
down_revision = 'fd7ed0458b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_system_timestamps',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_system_timestamps_name'), 'service_system_timestamps', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_system_timestamps_name'), table_name='service_system_timestamps')
    op.drop_table('service_system_timestamps')
    # ### end Alembic commands ###
