"""Removed log relation from notification

Revision ID: 38f83a8a363e
Revises: b780ca34cfaa
Create Date: 2024-02-10 18:40:06.808547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f83a8a363e'
down_revision = 'b780ca34cfaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_notifications_log_id_fkey', 'service_notifications', type_='foreignkey')
    op.drop_column('service_notifications', 'log_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_notifications', sa.Column('log_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('service_notifications_log_id_fkey', 'service_notifications', 'service_logs', ['log_id'], ['id'])
    # ### end Alembic commands ###
