"""Added private field to collection

Revision ID: 43418cadd4f4
Revises: 977e1c7a1f9a
Create Date: 2024-02-24 22:09:00.535855

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43418cadd4f4"
down_revision = "977e1c7a1f9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_collections",
        sa.Column(
            "private", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_collections", "private")
    # ### end Alembic commands ###
