"""Added system ranking field for collection

Revision ID: 78e40095870a
Revises: 3272fdea9aed
Create Date: 2024-03-26 00:08:32.638299

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78e40095870a"
down_revision = "3272fdea9aed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_collections",
        sa.Column(
            "system_ranking", sa.Float(), server_default="0", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_service_collections_system_ranking"),
        "service_collections",
        ["system_ranking"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_service_collections_system_ranking"),
        table_name="service_collections",
    )
    op.drop_column("service_collections", "system_ranking")
    # ### end Alembic commands ###
