"""Fixed edit stats model

Revision ID: 8e997ebbcbed
Revises: 8da1c939c781
Create Date: 2024-03-16 19:57:05.272006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e997ebbcbed'
down_revision = '8da1c939c781'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_stats_edits', sa.Column('accepted', sa.Integer(), nullable=False))
    op.add_column('service_stats_edits', sa.Column('closed', sa.Integer(), nullable=False))
    op.add_column('service_stats_edits', sa.Column('denied', sa.Integer(), nullable=False))
    op.drop_column('service_stats_edits', 'update')
    op.drop_column('service_stats_edits', 'deny')
    op.drop_column('service_stats_edits', 'create')
    op.drop_column('service_stats_edits', 'close')
    op.drop_column('service_stats_edits', 'accept')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_stats_edits', sa.Column('accept', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service_stats_edits', sa.Column('close', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service_stats_edits', sa.Column('create', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service_stats_edits', sa.Column('deny', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service_stats_edits', sa.Column('update', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('service_stats_edits', 'denied')
    op.drop_column('service_stats_edits', 'closed')
    op.drop_column('service_stats_edits', 'accepted')
    # ### end Alembic commands ###
