"""Added labels_order to collection

Revision ID: 9ed39a60e42b
Revises: 8604811ee56b
Create Date: 2024-02-23 14:21:36.715806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ed39a60e42b'
down_revision = '8604811ee56b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_collections', sa.Column('labels_order', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('service_collections', 'labels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_collections', sa.Column('labels', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('service_collections', 'labels_order')
    # ### end Alembic commands ###
