"""Renamed activity -> log

Revision ID: a14c062f24fb
Revises: 89282e47802e
Create Date: 2024-02-05 23:21:51.856824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a14c062f24fb'
down_revision = '89282e47802e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_logs',
    sa.Column('log_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_logs_log_type'), 'service_logs', ['log_type'], unique=False)
    op.drop_index('ix_service_activity_activity_type', table_name='service_activity')
    op.drop_table('service_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_activity',
    sa.Column('activity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], name='service_activity_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_activity_pkey')
    )
    op.create_index('ix_service_activity_activity_type', 'service_activity', ['activity_type'], unique=False)
    op.drop_index(op.f('ix_service_logs_log_type'), table_name='service_logs')
    op.drop_table('service_logs')
    # ### end Alembic commands ###
