"""Added search update field to user

Revision ID: a48975336cef
Revises: 994b4ace9fc0
Create Date: 2024-04-07 17:05:39.217270

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a48975336cef"
down_revision = "994b4ace9fc0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_users",
        sa.Column(
            "needs_search_update",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_users", "needs_search_update")
    # ### end Alembic commands ###
