"""Added updated field to anime schedule

Revision ID: a4bd5430b3d2
Revises: 70e6f448f5ae
Create Date: 2024-03-28 22:01:58.978875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bd5430b3d2'
down_revision = '70e6f448f5ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_schedule_anime', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_schedule_anime', 'updated')
    # ### end Alembic commands ###
