"""Added user activity model

Revision ID: cbe8a55da600
Revises: f2566cc5648e
Create Date: 2024-02-15 16:00:59.612322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbe8a55da600'
down_revision = 'f2566cc5648e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_user_activity',
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('used_logs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actions', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_user_activity_period'), 'service_user_activity', ['period'], unique=False)
    op.create_index(op.f('ix_service_user_activity_timestamp'), 'service_user_activity', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_user_activity_timestamp'), table_name='service_user_activity')
    op.drop_index(op.f('ix_service_user_activity_period'), table_name='service_user_activity')
    op.drop_table('service_user_activity')
    # ### end Alembic commands ###
