"""Added updated field to notification

Revision ID: d0add8734e1a
Revises: 6638db147bbb
Create Date: 2024-02-11 00:29:50.979418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0add8734e1a'
down_revision = '6638db147bbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_notifications', sa.Column('updated', sa.DateTime(), nullable=False))
    op.drop_index('ix_service_notifications_created', table_name='service_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service_notifications_created', 'service_notifications', ['created'], unique=False)
    op.drop_column('service_notifications', 'updated')
    # ### end Alembic commands ###
