"""Added vote_score field

Revision ID: efab6f4f4ba9
Revises: b861c733da4a
Create Date: 2024-03-22 02:10:00.624607

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "efab6f4f4ba9"
down_revision = "b861c733da4a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_collections",
        sa.Column(
            "vote_score", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "service_comments",
        sa.Column(
            "vote_score", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_comments", "vote_score")
    op.drop_column("service_collections", "vote_score")
    # ### end Alembic commands ###
