"""Initial revision

Revision ID: f1e35aec9d36
Revises: 
Create Date: 2023-12-18 21:24:49.336172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1e35aec9d36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_content_anime_franchises',
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_anime_franchises_content_id'), 'service_content_anime_franchises', ['content_id'], unique=True)
    op.create_table('service_content_anime_genres',
    sa.Column('name_en', sa.String(length=64), nullable=True),
    sa.Column('name_ua', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_anime_genres_content_id'), 'service_content_anime_genres', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_anime_genres_slug'), 'service_content_anime_genres', ['slug'], unique=False)
    op.create_index(op.f('ix_service_content_anime_genres_type'), 'service_content_anime_genres', ['type'], unique=False)
    op.create_table('service_content_anime_staff_roles',
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_ua', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_anime_staff_roles_slug'), 'service_content_anime_staff_roles', ['slug'], unique=False)
    op.create_table('service_images',
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.Column('ignore', sa.Boolean(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('service_users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(length=64), nullable=True),
    sa.Column('activation_expire', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expire', sa.DateTime(), nullable=True),
    sa.Column('last_username_change', sa.DateTime(), nullable=True),
    sa.Column('last_email_change', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('login', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_users_email'), 'service_users', ['email'], unique=False)
    op.create_index(op.f('ix_service_users_role'), 'service_users', ['role'], unique=False)
    op.create_index(op.f('ix_service_users_username'), 'service_users', ['username'], unique=False)
    op.create_table('service_auth_tokens',
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_auth_tokens_secret'), 'service_auth_tokens', ['secret'], unique=True)
    op.create_table('service_content_anime',
    sa.Column('title_ja', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('title_ua', sa.String(length=255), nullable=True),
    sa.Column('synopsis_en', sa.String(), nullable=True),
    sa.Column('synopsis_ua', sa.String(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('needs_update', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('season', sa.String(length=6), nullable=True),
    sa.Column('episodes_released', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('episodes_total', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('nsfw', sa.Boolean(), nullable=True),
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=True),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('videos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ost', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('poster_id', sa.Uuid(), nullable=True),
    sa.Column('franchise_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('ignored_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['franchise_id'], ['service_content_anime_franchises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['poster_id'], ['service_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_anime_content_id'), 'service_content_anime', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_anime_franchise_id'), 'service_content_anime', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_mal_id'), 'service_content_anime', ['mal_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_media_type'), 'service_content_anime', ['media_type'], unique=False)
    op.create_index(op.f('ix_service_content_anime_poster_id'), 'service_content_anime', ['poster_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_rating'), 'service_content_anime', ['rating'], unique=False)
    op.create_index(op.f('ix_service_content_anime_season'), 'service_content_anime', ['season'], unique=False)
    op.create_index(op.f('ix_service_content_anime_slug'), 'service_content_anime', ['slug'], unique=False)
    op.create_index(op.f('ix_service_content_anime_source'), 'service_content_anime', ['source'], unique=False)
    op.create_index(op.f('ix_service_content_anime_status'), 'service_content_anime', ['status'], unique=False)
    op.create_index(op.f('ix_service_content_anime_year'), 'service_content_anime', ['year'], unique=False)
    op.create_table('service_content_characters',
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name_ja', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_ua', sa.String(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_characters_content_id'), 'service_content_characters', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_characters_image_id'), 'service_content_characters', ['image_id'], unique=False)
    op.create_index(op.f('ix_service_content_characters_slug'), 'service_content_characters', ['slug'], unique=False)
    op.create_table('service_content_companies',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_companies_content_id'), 'service_content_companies', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_companies_image_id'), 'service_content_companies', ['image_id'], unique=False)
    op.create_index(op.f('ix_service_content_companies_slug'), 'service_content_companies', ['slug'], unique=False)
    op.create_table('service_content_people',
    sa.Column('name_native', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_ua', sa.String(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['service_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_people_content_id'), 'service_content_people', ['content_id'], unique=True)
    op.create_index(op.f('ix_service_content_people_image_id'), 'service_content_people', ['image_id'], unique=False)
    op.create_index(op.f('ix_service_content_people_slug'), 'service_content_people', ['slug'], unique=False)
    op.create_table('service_edits',
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('edit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('moderator_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['service_users.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('edit_id', 'id')
    )
    op.create_index(op.f('ix_service_edits_edit_id'), 'service_edits', ['edit_id'], unique=True)
    op.create_table('service_email_messages',
    sa.Column('sent_time', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_follows',
    sa.Column('followed_user_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['service_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('followed_user_id', 'user_id')
    )
    op.create_table('service_user_oauth',
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('oauth_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_content_anime_characters',
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('main', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['service_content_characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'anime_id')
    )
    op.create_index(op.f('ix_service_content_anime_characters_anime_id'), 'service_content_anime_characters', ['anime_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_characters_character_id'), 'service_content_anime_characters', ['character_id'], unique=False)
    op.create_table('service_content_anime_episodes',
    sa.Column('title_native', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('aired', sa.DateTime(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title_ja', sa.String(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('title_ua', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_anime_episodes_anime_id'), 'service_content_anime_episodes', ['anime_id'], unique=False)
    op.create_table('service_content_anime_recommendations',
    sa.Column('recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['service_content_anime.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'anime_id')
    )
    op.create_index(op.f('ix_service_content_anime_recommendations_anime_id'), 'service_content_anime_recommendations', ['anime_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_recommendations_recommendation_id'), 'service_content_anime_recommendations', ['recommendation_id'], unique=False)
    op.create_table('service_content_anime_staff',
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['service_content_people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'anime_id')
    )
    op.create_index(op.f('ix_service_content_anime_staff_anime_id'), 'service_content_anime_staff', ['anime_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_staff_person_id'), 'service_content_anime_staff', ['person_id'], unique=False)
    op.create_table('service_content_anime_voices',
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['service_content_characters.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['service_content_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_content_anime_voices_anime_id'), 'service_content_anime_voices', ['anime_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_voices_character_id'), 'service_content_anime_voices', ['character_id'], unique=False)
    op.create_index(op.f('ix_service_content_anime_voices_language'), 'service_content_anime_voices', ['language'], unique=False)
    op.create_index(op.f('ix_service_content_anime_voices_person_id'), 'service_content_anime_voices', ['person_id'], unique=False)
    op.create_table('service_content_companies_anime',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['service_content_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'anime_id', 'type')
    )
    op.create_index(op.f('ix_service_content_companies_anime_type'), 'service_content_companies_anime', ['type'], unique=False)
    op.create_table('service_favourite_anime',
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'user_id')
    )
    op.create_table('service_relation_anime_genres',
    sa.Column('anime_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['service_content_anime_genres.id'], ),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_table('service_watch',
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['service_content_anime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'user_id')
    )
    op.create_table('service_relation_anime_staff_roles',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['service_content_anime_staff_roles.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['service_content_anime_staff.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_relation_anime_staff_roles')
    op.drop_table('service_watch')
    op.drop_table('service_relation_anime_genres')
    op.drop_table('service_favourite_anime')
    op.drop_index(op.f('ix_service_content_companies_anime_type'), table_name='service_content_companies_anime')
    op.drop_table('service_content_companies_anime')
    op.drop_index(op.f('ix_service_content_anime_voices_person_id'), table_name='service_content_anime_voices')
    op.drop_index(op.f('ix_service_content_anime_voices_language'), table_name='service_content_anime_voices')
    op.drop_index(op.f('ix_service_content_anime_voices_character_id'), table_name='service_content_anime_voices')
    op.drop_index(op.f('ix_service_content_anime_voices_anime_id'), table_name='service_content_anime_voices')
    op.drop_table('service_content_anime_voices')
    op.drop_index(op.f('ix_service_content_anime_staff_person_id'), table_name='service_content_anime_staff')
    op.drop_index(op.f('ix_service_content_anime_staff_anime_id'), table_name='service_content_anime_staff')
    op.drop_table('service_content_anime_staff')
    op.drop_index(op.f('ix_service_content_anime_recommendations_recommendation_id'), table_name='service_content_anime_recommendations')
    op.drop_index(op.f('ix_service_content_anime_recommendations_anime_id'), table_name='service_content_anime_recommendations')
    op.drop_table('service_content_anime_recommendations')
    op.drop_index(op.f('ix_service_content_anime_episodes_anime_id'), table_name='service_content_anime_episodes')
    op.drop_table('service_content_anime_episodes')
    op.drop_index(op.f('ix_service_content_anime_characters_character_id'), table_name='service_content_anime_characters')
    op.drop_index(op.f('ix_service_content_anime_characters_anime_id'), table_name='service_content_anime_characters')
    op.drop_table('service_content_anime_characters')
    op.drop_table('service_user_oauth')
    op.drop_table('service_follows')
    op.drop_table('service_email_messages')
    op.drop_index(op.f('ix_service_edits_edit_id'), table_name='service_edits')
    op.drop_table('service_edits')
    op.drop_index(op.f('ix_service_content_people_slug'), table_name='service_content_people')
    op.drop_index(op.f('ix_service_content_people_image_id'), table_name='service_content_people')
    op.drop_index(op.f('ix_service_content_people_content_id'), table_name='service_content_people')
    op.drop_table('service_content_people')
    op.drop_index(op.f('ix_service_content_companies_slug'), table_name='service_content_companies')
    op.drop_index(op.f('ix_service_content_companies_image_id'), table_name='service_content_companies')
    op.drop_index(op.f('ix_service_content_companies_content_id'), table_name='service_content_companies')
    op.drop_table('service_content_companies')
    op.drop_index(op.f('ix_service_content_characters_slug'), table_name='service_content_characters')
    op.drop_index(op.f('ix_service_content_characters_image_id'), table_name='service_content_characters')
    op.drop_index(op.f('ix_service_content_characters_content_id'), table_name='service_content_characters')
    op.drop_table('service_content_characters')
    op.drop_index(op.f('ix_service_content_anime_year'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_status'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_source'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_slug'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_season'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_rating'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_poster_id'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_media_type'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_mal_id'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_franchise_id'), table_name='service_content_anime')
    op.drop_index(op.f('ix_service_content_anime_content_id'), table_name='service_content_anime')
    op.drop_table('service_content_anime')
    op.drop_index(op.f('ix_service_auth_tokens_secret'), table_name='service_auth_tokens')
    op.drop_table('service_auth_tokens')
    op.drop_index(op.f('ix_service_users_username'), table_name='service_users')
    op.drop_index(op.f('ix_service_users_role'), table_name='service_users')
    op.drop_index(op.f('ix_service_users_email'), table_name='service_users')
    op.drop_table('service_users')
    op.drop_table('service_images')
    op.drop_index(op.f('ix_service_content_anime_staff_roles_slug'), table_name='service_content_anime_staff_roles')
    op.drop_table('service_content_anime_staff_roles')
    op.drop_index(op.f('ix_service_content_anime_genres_type'), table_name='service_content_anime_genres')
    op.drop_index(op.f('ix_service_content_anime_genres_slug'), table_name='service_content_anime_genres')
    op.drop_index(op.f('ix_service_content_anime_genres_content_id'), table_name='service_content_anime_genres')
    op.drop_table('service_content_anime_genres')
    op.drop_index(op.f('ix_service_content_anime_franchises_content_id'), table_name='service_content_anime_franchises')
    op.drop_table('service_content_anime_franchises')
    # ### end Alembic commands ###
