"""Added duration field to watch

Revision ID: f2566cc5648e
Revises: 9dfe86b9e932
Create Date: 2024-02-13 16:24:58.565125

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2566cc5648e"
down_revision = "9dfe86b9e932"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_notifications", "target_id")
    op.add_column(
        "service_watch",
        sa.Column("duration", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_watch", "duration")
    op.add_column(
        "service_notifications",
        sa.Column("target_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
