"""Added index for created field in logs

Revision ID: f7bcaacbff28
Revises: a14c062f24fb
Create Date: 2024-02-06 23:25:47.440398

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "f7bcaacbff28"
down_revision = "a14c062f24fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_service_logs_created"),
        "service_logs",
        ["created"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_logs_created"), table_name="service_logs")
    # ### end Alembic commands ###
